# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QT/ADP/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(772, 555)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 751, 481))
        self.tabWidget.setObjectName("tabWidget")
        self.syncTab = QtWidgets.QWidget()
        self.syncTab.setObjectName("syncTab")
        self.getVCDataButton = QtWidgets.QPushButton(self.syncTab)
        self.getVCDataButton.setGeometry(QtCore.QRect(10, 10, 161, 41))
        self.getVCDataButton.setObjectName("getVCDataButton")
        self.logo_label = QtWidgets.QLabel(self.syncTab)
        self.logo_label.setGeometry(QtCore.QRect(630, 10, 100, 100))
        self.logo_label.setText("")
        self.logo_label.setObjectName("logo_label")
        self.vcDataStatusLabel = QtWidgets.QLabel(self.syncTab)
        self.vcDataStatusLabel.setGeometry(QtCore.QRect(180, 20, 20, 20))
        self.vcDataStatusLabel.setText("")
        self.vcDataStatusLabel.setObjectName("vcDataStatusLabel")
        self.vcRecordCount = QtWidgets.QLabel(self.syncTab)
        self.vcRecordCount.setGeometry(QtCore.QRect(220, 20, 101, 20))
        self.vcRecordCount.setObjectName("vcRecordCount")
        self.parseVCDataButton = QtWidgets.QPushButton(self.syncTab)
        self.parseVCDataButton.setGeometry(QtCore.QRect(10, 60, 161, 41))
        self.parseVCDataButton.setObjectName("parseVCDataButton")
        self.vcParseStatusLabel = QtWidgets.QLabel(self.syncTab)
        self.vcParseStatusLabel.setGeometry(QtCore.QRect(180, 70, 20, 20))
        self.vcParseStatusLabel.setText("")
        self.vcParseStatusLabel.setObjectName("vcParseStatusLabel")
        self.tabWidget.addTab(self.syncTab, "")
        self.resultsTab = QtWidgets.QWidget()
        self.resultsTab.setObjectName("resultsTab")
        self.resultsTextEdit = QtWidgets.QTextEdit(self.resultsTab)
        self.resultsTextEdit.setGeometry(QtCore.QRect(10, 10, 721, 431))
        self.resultsTextEdit.setObjectName("resultsTextEdit")
        self.tabWidget.addTab(self.resultsTab, "")
        self.settingsTab = QtWidgets.QWidget()
        self.settingsTab.setObjectName("settingsTab")
        self.vc_api_user = QtWidgets.QLineEdit(self.settingsTab)
        self.vc_api_user.setGeometry(QtCore.QRect(230, 30, 291, 21))
        self.vc_api_user.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.vc_api_user.setObjectName("vc_api_user")
        self.label = QtWidgets.QLabel(self.settingsTab)
        self.label.setGeometry(QtCore.QRect(30, 30, 191, 21))
        self.label.setObjectName("label")
        self.vc_api_pass = QtWidgets.QLineEdit(self.settingsTab)
        self.vc_api_pass.setGeometry(QtCore.QRect(230, 70, 291, 21))
        self.vc_api_pass.setText("")
        self.vc_api_pass.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.vc_api_pass.setObjectName("vc_api_pass")
        self.label_2 = QtWidgets.QLabel(self.settingsTab)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 191, 21))
        self.label_2.setObjectName("label_2")
        self.vc_api_url = QtWidgets.QLineEdit(self.settingsTab)
        self.vc_api_url.setGeometry(QtCore.QRect(230, 110, 291, 21))
        self.vc_api_url.setObjectName("vc_api_url")
        self.label_3 = QtWidgets.QLabel(self.settingsTab)
        self.label_3.setGeometry(QtCore.QRect(30, 110, 191, 21))
        self.label_3.setObjectName("label_3")
        self.settingsSave = QtWidgets.QPushButton(self.settingsTab)
        self.settingsSave.setGeometry(QtCore.QRect(580, 410, 161, 41))
        self.settingsSave.setObjectName("settingsSave")
        self.tabWidget.addTab(self.settingsTab, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Veracross to ADP Sync"))
        self.getVCDataButton.setText(_translate("MainWindow", "Get Veracross Data"))
        self.vcRecordCount.setText(_translate("MainWindow", "0 Records"))
        self.parseVCDataButton.setText(_translate("MainWindow", "Parse Veracross Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.syncTab), _translate("MainWindow", "Sync"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.resultsTab), _translate("MainWindow", "Results"))
        self.label.setText(_translate("MainWindow", "Veracross API Username"))
        self.label_2.setText(_translate("MainWindow", "Veracross API Password"))
        self.label_3.setText(_translate("MainWindow", "Veracross API Base URL"))
        self.settingsSave.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingsTab), _translate("MainWindow", "Settings"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

