# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QT/ADP/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(772, 555)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabs = QtWidgets.QTabWidget(self.centralWidget)
        self.tabs.setGeometry(QtCore.QRect(10, 20, 751, 481))
        self.tabs.setObjectName("tabs")
        self.syncTab = QtWidgets.QWidget()
        self.syncTab.setObjectName("syncTab")
        self.logo_label = QtWidgets.QLabel(self.syncTab)
        self.logo_label.setGeometry(QtCore.QRect(599, 10, 131, 131))
        self.logo_label.setText("")
        self.logo_label.setObjectName("logo_label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.syncTab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 541, 134))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.vcFSRecordCount = QtWidgets.QLabel(self.gridLayoutWidget)
        self.vcFSRecordCount.setObjectName("vcFSRecordCount")
        self.gridLayout.addWidget(self.vcFSRecordCount, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.progressBarGetVCData = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBarGetVCData.setProperty("value", 24)
        self.progressBarGetVCData.setObjectName("progressBarGetVCData")
        self.gridLayout.addWidget(self.progressBarGetVCData, 0, 2, 1, 1)
        self.adpRecordCount = QtWidgets.QLabel(self.gridLayoutWidget)
        self.adpRecordCount.setObjectName("adpRecordCount")
        self.gridLayout.addWidget(self.adpRecordCount, 2, 1, 1, 1)
        self.progressBarParseVCData = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBarParseVCData.setProperty("value", 24)
        self.progressBarParseVCData.setObjectName("progressBarParseVCData")
        self.gridLayout.addWidget(self.progressBarParseVCData, 1, 2, 1, 1)
        self.progressBarGetADPData = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBarGetADPData.setProperty("value", 24)
        self.progressBarGetADPData.setObjectName("progressBarGetADPData")
        self.gridLayout.addWidget(self.progressBarGetADPData, 2, 2, 1, 1)
        self.progressBarParseADPData = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBarParseADPData.setProperty("value", 24)
        self.progressBarParseADPData.setObjectName("progressBarParseADPData")
        self.gridLayout.addWidget(self.progressBarParseADPData, 3, 2, 1, 1)
        self.btn_sync = QtWidgets.QPushButton(self.syncTab)
        self.btn_sync.setGeometry(QtCore.QRect(0, 390, 245, 50))
        self.btn_sync.setObjectName("btn_sync")
        self.btn_quit = QtWidgets.QPushButton(self.syncTab)
        self.btn_quit.setGeometry(QtCore.QRect(500, 390, 245, 50))
        self.btn_quit.setObjectName("btn_quit")
        self.btn_commitToADP = QtWidgets.QPushButton(self.syncTab)
        self.btn_commitToADP.setGeometry(QtCore.QRect(250, 390, 245, 50))
        self.btn_commitToADP.setObjectName("btn_commitToADP")
        self.txt_SyncDataResults = QtWidgets.QPlainTextEdit(self.syncTab)
        self.txt_SyncDataResults.setGeometry(QtCore.QRect(10, 160, 721, 211))
        self.txt_SyncDataResults.setObjectName("txt_SyncDataResults")
        self.tabs.addTab(self.syncTab, "")
        self.resultsTab = QtWidgets.QWidget()
        self.resultsTab.setObjectName("resultsTab")
        self.vcResultsTextEdit = QtWidgets.QTextEdit(self.resultsTab)
        self.vcResultsTextEdit.setGeometry(QtCore.QRect(10, 60, 721, 181))
        self.vcResultsTextEdit.setObjectName("vcResultsTextEdit")
        self.btn_ResultsPrevious = QtWidgets.QPushButton(self.resultsTab)
        self.btn_ResultsPrevious.setGeometry(QtCore.QRect(500, 20, 113, 32))
        self.btn_ResultsPrevious.setObjectName("btn_ResultsPrevious")
        self.btn_ResultsNext = QtWidgets.QPushButton(self.resultsTab)
        self.btn_ResultsNext.setGeometry(QtCore.QRect(620, 20, 113, 32))
        self.btn_ResultsNext.setObjectName("btn_ResultsNext")
        self.adpResultsTextEdit = QtWidgets.QTextEdit(self.resultsTab)
        self.adpResultsTextEdit.setGeometry(QtCore.QRect(10, 270, 721, 181))
        self.adpResultsTextEdit.setObjectName("adpResultsTextEdit")
        self.label_2 = QtWidgets.QLabel(self.resultsTab)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 141, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.resultsTab)
        self.label_3.setGeometry(QtCore.QRect(10, 250, 141, 16))
        self.label_3.setObjectName("label_3")
        self.tabs.addTab(self.resultsTab, "")
        self.fieldMapTab = QtWidgets.QWidget()
        self.fieldMapTab.setObjectName("fieldMapTab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.fieldMapTab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 731, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.btn_saveFieldMap = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_saveFieldMap.setObjectName("btn_saveFieldMap")
        self.verticalLayout_3.addWidget(self.btn_saveFieldMap)
        self.txt_fieldMap = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.txt_fieldMap.setReadOnly(False)
        self.txt_fieldMap.setAcceptRichText(False)
        self.txt_fieldMap.setObjectName("txt_fieldMap")
        self.verticalLayout_3.addWidget(self.txt_fieldMap)
        self.tabs.addTab(self.fieldMapTab, "")
        self.settingsTab = QtWidgets.QWidget()
        self.settingsTab.setObjectName("settingsTab")
        self.settingsSave = QtWidgets.QPushButton(self.settingsTab)
        self.settingsSave.setGeometry(QtCore.QRect(580, 410, 161, 41))
        self.settingsSave.setObjectName("settingsSave")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.settingsTab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 731, 339))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_adpPassword = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_adpPassword.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.lineEdit_adpPassword.setObjectName("lineEdit_adpPassword")
        self.gridLayout_3.addWidget(self.lineEdit_adpPassword, 4, 1, 1, 1)
        self.lbl_adpNetworkPassword = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.lbl_adpNetworkPassword.setObjectName("lbl_adpNetworkPassword")
        self.gridLayout_3.addWidget(self.lbl_adpNetworkPassword, 4, 0, 1, 1)
        self.lineEdit_adpVCCustomFieldName = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_adpVCCustomFieldName.setObjectName("lineEdit_adpVCCustomFieldName")
        self.gridLayout_3.addWidget(self.lineEdit_adpVCCustomFieldName, 5, 1, 1, 1)
        self.lbl_CertificatePath = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.lbl_CertificatePath.setObjectName("lbl_CertificatePath")
        self.gridLayout_3.addWidget(self.lbl_CertificatePath, 7, 0, 1, 1)
        self.lineEdit_adpUsername = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_adpUsername.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.lineEdit_adpUsername.setObjectName("lineEdit_adpUsername")
        self.gridLayout_3.addWidget(self.lineEdit_adpUsername, 3, 1, 1, 1)
        self.lineEdit_adpCertificatePEMPath = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_adpCertificatePEMPath.setObjectName("lineEdit_adpCertificatePEMPath")
        self.gridLayout_3.addWidget(self.lineEdit_adpCertificatePEMPath, 7, 1, 1, 1)
        self.lbl_vcpassword = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.lbl_vcpassword.setObjectName("lbl_vcpassword")
        self.gridLayout_3.addWidget(self.lbl_vcpassword, 1, 0, 1, 1)
        self.lbl_vcapiusername = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.lbl_vcapiusername.setObjectName("lbl_vcapiusername")
        self.gridLayout_3.addWidget(self.lbl_vcapiusername, 0, 0, 1, 1)
        self.vc_api_user = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.vc_api_user.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.vc_api_user.setObjectName("vc_api_user")
        self.gridLayout_3.addWidget(self.vc_api_user, 0, 1, 1, 1)
        self.vc_api_pass = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.vc_api_pass.setText("")
        self.vc_api_pass.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.vc_api_pass.setObjectName("vc_api_pass")
        self.gridLayout_3.addWidget(self.vc_api_pass, 1, 1, 1, 1)
        self.lbl_vcapiurl = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.lbl_vcapiurl.setObjectName("lbl_vcapiurl")
        self.gridLayout_3.addWidget(self.lbl_vcapiurl, 2, 0, 1, 1)
        self.vc_api_url = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.vc_api_url.setObjectName("vc_api_url")
        self.gridLayout_3.addWidget(self.vc_api_url, 2, 1, 1, 1)
        self.lbl_adpNetworkUsername = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.lbl_adpNetworkUsername.setObjectName("lbl_adpNetworkUsername")
        self.gridLayout_3.addWidget(self.lbl_adpNetworkUsername, 3, 0, 1, 1)
        self.lineEdit_adpCertificateKeyPath = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_adpCertificateKeyPath.setObjectName("lineEdit_adpCertificateKeyPath")
        self.gridLayout_3.addWidget(self.lineEdit_adpCertificateKeyPath, 10, 1, 1, 1)
        self.lbl_CertificateKeyPath = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.lbl_CertificateKeyPath.setObjectName("lbl_CertificateKeyPath")
        self.gridLayout_3.addWidget(self.lbl_CertificateKeyPath, 10, 0, 1, 1)
        self.lbl_adpVCCustomFieldName = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.lbl_adpVCCustomFieldName.setObjectName("lbl_adpVCCustomFieldName")
        self.gridLayout_3.addWidget(self.lbl_adpVCCustomFieldName, 5, 0, 1, 1)
        self.btn_pickerADPCertificate = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_pickerADPCertificate.setObjectName("btn_pickerADPCertificate")
        self.gridLayout_3.addWidget(self.btn_pickerADPCertificate, 8, 0, 1, 1)
        self.btn_pickerADPCertificateKey = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_pickerADPCertificateKey.setObjectName("btn_pickerADPCertificateKey")
        self.gridLayout_3.addWidget(self.btn_pickerADPCertificateKey, 11, 0, 1, 1)
        self.tabs.addTab(self.settingsTab, "")
        self.debugTab = QtWidgets.QWidget()
        self.debugTab.setObjectName("debugTab")
        self.textLog = QtWidgets.QTextBrowser(self.debugTab)
        self.textLog.setGeometry(QtCore.QRect(10, 261, 731, 171))
        self.textLog.setObjectName("textLog")
        self.lbl_Log = QtWidgets.QLabel(self.debugTab)
        self.lbl_Log.setGeometry(QtCore.QRect(10, 240, 60, 16))
        self.lbl_Log.setObjectName("lbl_Log")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.debugTab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 511, 191))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.getVCDataButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.getVCDataButton.setEnabled(False)
        self.getVCDataButton.setObjectName("getVCDataButton")
        self.gridLayout_2.addWidget(self.getVCDataButton, 2, 1, 1, 1)
        self.lbl_vcLastXRateLimitReading = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbl_vcLastXRateLimitReading.setObjectName("lbl_vcLastXRateLimitReading")
        self.gridLayout_2.addWidget(self.lbl_vcLastXRateLimitReading, 0, 0, 1, 1)
        self.lineEditXRateLimitReading = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEditXRateLimitReading.setObjectName("lineEditXRateLimitReading")
        self.gridLayout_2.addWidget(self.lineEditXRateLimitReading, 0, 1, 1, 1)
        self.lbl_vcLastXRateResetReading = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbl_vcLastXRateResetReading.setObjectName("lbl_vcLastXRateResetReading")
        self.gridLayout_2.addWidget(self.lbl_vcLastXRateResetReading, 1, 0, 1, 1)
        self.lineEditXRateLimitResetReading = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEditXRateLimitResetReading.setObjectName("lineEditXRateLimitResetReading")
        self.gridLayout_2.addWidget(self.lineEditXRateLimitResetReading, 1, 1, 1, 1)
        self.btn_getADPData = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_getADPData.setEnabled(False)
        self.btn_getADPData.setObjectName("btn_getADPData")
        self.gridLayout_2.addWidget(self.btn_getADPData, 4, 1, 1, 1)
        self.parseVCDataButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.parseVCDataButton.setEnabled(False)
        self.parseVCDataButton.setObjectName("parseVCDataButton")
        self.gridLayout_2.addWidget(self.parseVCDataButton, 3, 1, 1, 1)
        self.btn_parseADPData = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_parseADPData.setEnabled(False)
        self.btn_parseADPData.setObjectName("btn_parseADPData")
        self.gridLayout_2.addWidget(self.btn_parseADPData, 5, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 5, 0, 1, 1)
        self.tabs.addTab(self.debugTab, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btn_saveFieldMap, self.txt_fieldMap)
        MainWindow.setTabOrder(self.txt_fieldMap, self.btn_ResultsPrevious)
        MainWindow.setTabOrder(self.btn_ResultsPrevious, self.btn_ResultsNext)
        MainWindow.setTabOrder(self.btn_ResultsNext, self.vcResultsTextEdit)
        MainWindow.setTabOrder(self.vcResultsTextEdit, self.vc_api_user)
        MainWindow.setTabOrder(self.vc_api_user, self.vc_api_pass)
        MainWindow.setTabOrder(self.vc_api_pass, self.vc_api_url)
        MainWindow.setTabOrder(self.vc_api_url, self.lineEdit_adpUsername)
        MainWindow.setTabOrder(self.lineEdit_adpUsername, self.lineEdit_adpCertificatePEMPath)
        MainWindow.setTabOrder(self.lineEdit_adpCertificatePEMPath, self.settingsSave)
        MainWindow.setTabOrder(self.settingsSave, self.lineEditXRateLimitReading)
        MainWindow.setTabOrder(self.lineEditXRateLimitReading, self.lineEditXRateLimitResetReading)
        MainWindow.setTabOrder(self.lineEditXRateLimitResetReading, self.textLog)
        MainWindow.setTabOrder(self.textLog, self.tabs)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Veracross to ADP Sync"))
        self.vcFSRecordCount.setStatusTip(_translate("MainWindow", "Records found in VC"))
        self.vcFSRecordCount.setText(_translate("MainWindow", "000000"))
        self.label_7.setText(_translate("MainWindow", "Parse ADP Data"))
        self.label_6.setText(_translate("MainWindow", "Get ADP Data"))
        self.label_5.setText(_translate("MainWindow", "Parse Veracross Data"))
        self.label_4.setText(_translate("MainWindow", "Get Veracross Data"))
        self.progressBarGetVCData.setStatusTip(_translate("MainWindow", "Progress of VC Pull"))
        self.adpRecordCount.setStatusTip(_translate("MainWindow", "Records found in ADP"))
        self.adpRecordCount.setText(_translate("MainWindow", "000000"))
        self.progressBarParseVCData.setStatusTip(_translate("MainWindow", "Progress of VC Data Parse"))
        self.progressBarGetADPData.setStatusTip(_translate("MainWindow", "Progress of ADP Data Pull"))
        self.progressBarParseADPData.setStatusTip(_translate("MainWindow", "Progress of ADP Data Parse"))
        self.btn_sync.setStatusTip(_translate("MainWindow", "Sync and Find Differences"))
        self.btn_sync.setText(_translate("MainWindow", "Sync"))
        self.btn_quit.setStatusTip(_translate("MainWindow", "Quit Application"))
        self.btn_quit.setText(_translate("MainWindow", "Quit"))
        self.btn_commitToADP.setStatusTip(_translate("MainWindow", "Commit Changes to ADP"))
        self.btn_commitToADP.setText(_translate("MainWindow", "Commit to ADP"))
        self.txt_SyncDataResults.setStatusTip(_translate("MainWindow", "Data differences ready to be commited to ADP"))
        self.tabs.setTabText(self.tabs.indexOf(self.syncTab), _translate("MainWindow", "Sync"))
        self.vcResultsTextEdit.setStatusTip(_translate("MainWindow", "Parsed Veracross Data Results "))
        self.btn_ResultsPrevious.setText(_translate("MainWindow", "Previous"))
        self.btn_ResultsNext.setText(_translate("MainWindow", "Next"))
        self.adpResultsTextEdit.setStatusTip(_translate("MainWindow", "ADP Parsed Data Results"))
        self.label_2.setText(_translate("MainWindow", "Veracross Results"))
        self.label_3.setText(_translate("MainWindow", "ADP Results"))
        self.tabs.setTabText(self.tabs.indexOf(self.resultsTab), _translate("MainWindow", "Results"))
        self.label.setText(_translate("MainWindow", "Insert field mapping. See README for formatting."))
        self.btn_saveFieldMap.setText(_translate("MainWindow", "Save"))
        self.txt_fieldMap.setStatusTip(_translate("MainWindow", "Field mappings"))
        self.tabs.setTabText(self.tabs.indexOf(self.fieldMapTab), _translate("MainWindow", "Map Fields"))
        self.settingsSave.setText(_translate("MainWindow", "Save"))
        self.lbl_adpNetworkPassword.setToolTip(_translate("MainWindow", "ADP Network Password provided by ADP."))
        self.lbl_adpNetworkPassword.setText(_translate("MainWindow", "ADP Network Password"))
        self.lbl_CertificatePath.setToolTip(_translate("MainWindow", "Path to Base64 encoded certificate provided by ADP."))
        self.lbl_CertificatePath.setText(_translate("MainWindow", "ADP Certificate (PEM)"))
        self.lbl_vcpassword.setToolTip(_translate("MainWindow", "Veracross API Password provided by Veracross."))
        self.lbl_vcpassword.setText(_translate("MainWindow", "Veracross API Password"))
        self.lbl_vcapiusername.setToolTip(_translate("MainWindow", "Veracross API Username provided by Veracross."))
        self.lbl_vcapiusername.setText(_translate("MainWindow", "Veracross API Username"))
        self.lbl_vcapiurl.setToolTip(_translate("MainWindow", "Veracross API Base URL."))
        self.lbl_vcapiurl.setText(_translate("MainWindow", "Veracross API Base URL"))
        self.lbl_adpNetworkUsername.setToolTip(_translate("MainWindow", "ADP Network Username provided by ADP."))
        self.lbl_adpNetworkUsername.setText(_translate("MainWindow", "ADP Network Username"))
        self.lbl_CertificateKeyPath.setToolTip(_translate("MainWindow", "Certificate file used to create ADP certificate above."))
        self.lbl_CertificateKeyPath.setText(_translate("MainWindow", "ADP Certificate Key"))
        self.lbl_adpVCCustomFieldName.setToolTip(_translate("MainWindow", "Name of custom field in ADP where the Veracross ID is stored."))
        self.lbl_adpVCCustomFieldName.setText(_translate("MainWindow", "ADP VC Custom Field Name"))
        self.btn_pickerADPCertificate.setText(_translate("MainWindow", "Select Certificate"))
        self.btn_pickerADPCertificateKey.setText(_translate("MainWindow", "Select Certificate Key"))
        self.tabs.setTabText(self.tabs.indexOf(self.settingsTab), _translate("MainWindow", "Settings"))
        self.lbl_Log.setText(_translate("MainWindow", "Log"))
        self.getVCDataButton.setText(_translate("MainWindow", "Get Veracross Data"))
        self.lbl_vcLastXRateLimitReading.setText(_translate("MainWindow", "Veracross Last X-Rate-Limit-Remaining Reading"))
        self.lbl_vcLastXRateResetReading.setText(_translate("MainWindow", "Veracross Last X-Rate-Limit-Reset Reading"))
        self.btn_getADPData.setText(_translate("MainWindow", "Get ADP Data"))
        self.parseVCDataButton.setText(_translate("MainWindow", "Parse Veracross Data"))
        self.btn_parseADPData.setText(_translate("MainWindow", "Parse ADP Data"))
        self.label_8.setText(_translate("MainWindow", "Test Getting Veracross Data"))
        self.label_9.setText(_translate("MainWindow", "Test Parsing Veracross Data"))
        self.label_10.setText(_translate("MainWindow", "Test Getting ADP Data"))
        self.label_11.setText(_translate("MainWindow", "Test Parsing ADP Data"))
        self.tabs.setTabText(self.tabs.indexOf(self.debugTab), _translate("MainWindow", "Debug"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

